### PR TITLE
Update Allameh Jafari station information

### PR DESCRIPTION
**Pull request by MohammadGhaderi0**
Completed missing fields for Allameh Jafari station, including WC, coffee shop, and ATM details.

### CODE REVIEW

**Comment by ArmanTaheriGhaleTaki** [comment]
Is the WC available for subway passengers? are you sure about that?

**Comment by MohammadGhaderi0** [comment]
> Is the WC available for subway passengers? are you sure about that?

I haven't used the WC there, but I think I saw the sign next to the praying room. If you're sure, please let me know so I can change it

**Comment by ArmanTaheriGhaleTaki** [comment]
There is a corridor that always seems to be locked and only accessible to staff. I'm not sure if it is available to passengers.

**Comment by MohammadGhaderi0** [comment]
Ok, to avoid providing incorrect information, I removed the line about the WC.

**Pull request merged**
